### PR TITLE
Readding cython

### PR DESCRIPTION
**Pull request by HeavyTony2**
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=638201&view=logs&jobId=656edd35-690f-5c53-9ba3-09c10d0bea97&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d https://github.com/conda-forge/pyload-ng-feedstock/pull/13
https://github.com/conda-forge/arm_pyart-feedstock/pull/69
```
done
export PREFIX=/home/conda/feedstock_root/build_artifacts/pyload-ng_1673231912364/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh
export SRC_DIR=/home/conda/feedstock_root/build_artifacts/pyload-ng_1673231912364/test_tmp
import: 'pyload'
import: 'pyload'
+ pip check
arm-pyart 0.0.0 requires cython, which is not installed.
Tests failed for pyload-ng-0.5.0b3.dev35-pyhf91719a_0.conda - moving package to /home/conda/feedstock_root/build_artifacts/broken
WARNING:conda_build.build:Tests failed for pyload-ng-0.5.0b3.dev35-pyhf91719a_0.conda - moving package to /home/conda/feedstock_root/build_artifacts/broken
TESTS FAILED: pyload-ng-0.5.0b3.dev35-pyhf91719a_0.conda
```

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by zssherman** [comment]
@HeavyTony2, @mgrover1 and I are trying to figure this one out. Wondering why its showing pyart as 0.0.0 version, wondering if there is a versioning issue. The more we looked at it, don't think cython is used on the run side of things. We are still looking.

**Comment by HeavyTony2** [comment]
> @HeavyTony2, @mgrover1 and I are trying to figure this one out. Wondering why its showing pyart as 0.0.0 version, wondering if there is a versioning issue. The more we looked at it, don't think cython is used on the run side of things. We are still looking.

Thanks

**Comment by mgrover1** [comment]
@HeavyTony2 - the issues are caused by the mismatch between the requirements from pypi and our meta.yml file. We are working on PR to change the requirements vs. build requirements for the Py-ART project on pypi. 

What are you using Py-ART for in your project?

**Comment by zssherman** [comment]
@HeavyTony2 The cython in the requirements etc should be removed now. Going to do a microrelease, which hopefully will resolve this issue.

**Comment by mgrover1** [comment]
@HeavyTony2 can you try your build again with the updated Py-ART conda-forge release which removes cython?

**Comment by HeavyTony2** [comment]
> @HeavyTony2 can you try your build again with the updated Py-ART conda-forge release which removes cython?

It did work, thanks

**Pull request closed without merging**
