### PR TITLE
Py-ART V1.12.6

### PR DESCRIPTION
**Pull request by zssherman**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mgrover1** [comment]
We just need to update the numpy and cftime pinnings

**Comment by zssherman** [comment]
@mgrover1 I removed the numpy pin and cftime isn't referenced, should i add cftime to run and add >=1.6.0?

**Comment by zssherman** [comment]
It seems to almost be a render issue, using unique python versions...

**Comment by zssherman** [comment]
@mgrover1 Tests seem to be passing now with pinning.

**Review by mgrover1 — APPROVED** [review]
Great! Thanks for putting this together

**Pull request merged**
