### PR TITLE
Adding cython to running

### PR DESCRIPTION
**Pull request by HeavyTony2**
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=582589&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=3687

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=582589&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=3687

### CODE REVIEW

**Comment by HeavyTony2** [comment]
@conda-forge-admin, please rerender

**Review by mgrover1 — APPROVED** [review]

**Review by zssherman — APPROVED** [review]

**Comment by zssherman** [comment]
Thanks @HeavyTony2 for the PR! Merging

**Comment by HeavyTony2** [comment]
> Thanks @HeavyTony2 for the PR! Merging

Thanks to both of you

**Comment by dopplershift** [comment]
Can someone shed some light on why this was necessary? Looking at the pyart source I don't see any use of Cython at runtime?

**Comment by HeavyTony2** [comment]
> Can someone shed some light on why this was necessary? Looking at the pyart source I don't see any use of Cython at runtime?

I  see I posted a (now dead) link for a built that failed. Probably the building was failing at the test phase because pipcheck said Cython was required by arm-pyart.

**Comment by dopplershift** [comment]
If that's the case, I'm still confused why pyart itself wasn't updated to remove it listing cython as a runtime dependency?

**Comment by dopplershift** [comment]
(that's probably more to @mgrover1 and @zssherman )

**Comment by zssherman** [comment]
@dopplershift, I can do a release and remove the cython from the run, missed it on my part. Before that though, I will try to updated that warning issued you raised. I'll goes those both fixed

**Comment by dopplershift** [comment]
No worries on those, it was more a matter of installing pyart into an environment, seeing it add cython, and saying "Well that's seems weird".  Thanks @zssherman !

**Comment by zssherman** [comment]
Thanks for catching those!

**Comment by HeavyTony2** [comment]
```
done
export PREFIX=/home/conda/feedstock_root/build_artifacts/pyload-ng_1673231912364/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh
export SRC_DIR=/home/conda/feedstock_root/build_artifacts/pyload-ng_1673231912364/test_tmp
import: 'pyload'
import: 'pyload'
+ pip check
arm-pyart 0.0.0 requires cython, which is not installed.
Tests failed for pyload-ng-0.5.0b3.dev35-pyhf91719a_0.conda - moving package to /home/conda/feedstock_root/build_artifacts/broken
WARNING:conda_build.build:Tests failed for pyload-ng-0.5.0b3.dev35-pyhf91719a_0.conda - moving package to /home/conda/feedstock_root/build_artifacts/broken
TESTS FAILED: pyload-ng-0.5.0b3.dev35-pyhf91719a_0.conda

```
I just got an example of why I made this PR.
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=638201&view=logs&jobId=656edd35-690f-5c53-9ba3-09c10d0bea97&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d

https://github.com/conda-forge/pyload-ng-feedstock/pull/13/checks?check_run_id=10515250228

https://github.com/conda-forge/pyload-ng-feedstock/pull/13/

**Pull request merged**
