### PR TITLE
Py-ART Version 1.9.0

### PR DESCRIPTION
**Pull request by zssherman**

### CODE REVIEW

**Comment by scollis** [comment]
So @jjhelmus @zssherman what is the go with this?
I see that in Appveyor on py3.5 most pass...
fail seems to be this:
`LINK : fatal error LNK1181: cannot open input file 'flang.lib'
`
All travis passes. and the linter seems to be more of a warning for us to fix on next release..

**Comment by jjhelmus** [comment]
The Python 3.5 and 3.6 failures are discussed in conda-forge/numpy-feedstock#79.  Switching to the numpy pinning approach described in the [conda-forge docs](https://conda-forge.org/docs/meta.html#building-against-numpy) is the best solution to this and will create packages which will work with future versions of NumPy.

**Comment by scollis** [comment]
Thanks @jjhelmus is this something we can do now? Thanks for your time.

**Comment by scollis** [comment]
Looks like it is here @zssherman https://github.com/conda-forge/arm_pyart-feedstock/blob/master/recipe/meta.yaml#L17

**Comment by jjhelmus** [comment]
Update the recipe to use the following in the requirement section and rerender the feedstock.

``` yaml
requirements:
    build:
        - python
        - numpy 1.11.*
        - trmm_rsl  # [not win]

    run:
        - python
        - numpy >= 1.11
        - scipy
        - matplotlib
        - netcdf4
        - trmm_rsl  # [not win]
```

Alternatively, you can use the other pinning described in the document, although I suspect that Py-ART may have issues with NumPy less than 1.11.

**Comment by zssherman** [comment]
@jjhelmus Thanks Jonathan! I'll update the yml and i'll rerun the conda-rerender and make a new push with both commits.

**Comment by scollis** [comment]
You've made the linter happy! That is a really nice email :)

**Comment by jjhelmus** [comment]
@zssherman Do you want to add yourself as a maintainer in the meta.yaml?  That way you can merge these yourself in the future.

**Comment by zssherman** [comment]
@jjhelmus That would be great! I'll add the - zssherman under recipe-maintainers. Should I rerender with conda smithy too?

**Comment by jjhelmus** [comment]
> Should I rerender with conda smithy too?

Nothing should change so rerending is not needed.

**Comment by zssherman** [comment]
Ok awesome! I will commit the meta.yml.

**Comment by scollis** [comment]
Ping @jjhelmus ...
We are all green!

**Pull request merged**
